# Generated by Django 2.1.5 on 2019-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumodeagua',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('Litros', models.FloatField(blank=True, db_column='Litros', null=True)),
                ('Fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
            ],
            options={
                'db_table': 'ConsumoDeAgua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('Humedad', models.IntegerField(blank=True, db_column='Humedad', null=True)),
                ('Lluvia', models.IntegerField(blank=True, db_column='Lluvia', null=True)),
                ('Encendido', models.IntegerField(blank=True, db_column='Encendido', null=True)),
            ],
            options={
                'db_table': 'Propiedades',
                'managed': False,
            },
        ),
    ]
