# Generated by Django 2.1.5 on 2019-05-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0002_auto_20190527_2015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumodeagua',
            table='ConsumoDeAgua',
        ),
    ]
